OMZigak/KKUYOS

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum/Resource/Base/BaseCollectionReusableView.swift
KkuMulKum/Resource/Base/BaseCollectionViewCell.swift
KkuMulKum/Resource/Base/BaseTableViewCell.swift
KkuMulKum/Resource/Base/BaseView.swift
KkuMulKum/Resource/Base/BaseViewController.swift

- Connected: #113 
- UI를 구현할 때, 기반이 될 [Base UI 클래스 코드](https://arrow-frog-4b9.notion.site/UI-Base-UI-Code-e1376c0752e14bcebb524f148339b31b?pvs=4)를 구현하였습니다.
- `import Then`은 BaseView.swift 파일에 같이 적어두었습니다.

[add] Base 클래스 추가

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum/Network/MoyaLoggingPlugin.swift
KkuMulKum/Resource/ObservablePattern/ObservablePattern.swift

- Connected: #119 
- ObservablePattern 코드 추가
- MoyaLoggingPlugin 코드 추가
|    구현 내용    |     |
| 현재 폴더 구조 | <img src = "https://github.com/OMZigak/iOS/assets/91656206/1fbf320e-90d3-4543-94b1-500fbcb49bbc" width ="250"> |
- 클로저의 `[weak self]`에서 `guard let self else { return }` 구문을 생략하기 위한 또 다른 `bind` 메서드를 구현하였습니다.
<details>
<summary>ObservablePattern.swift</summary>
```swift
class ObservablePattern<T> {
var value: T {
didSet {
listener?(value)
}
}
private var listener: ((T) -> Void)?
init(_ value: T) {
self.value = value
}
func bind(_ listener: @escaping (T) -> Void) {
self.listener = listener
}
func bind<Object: AnyObject>(with object: Object, _ listener: @escaping (Object, T) -> Void) {
self.listener = { [weak object] value in
guard let object else { …
```

[add] ObservablePattern, MoyaLoggingPlugin 추가

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum/KkuMulKum.entitlements

- Connected: #116 
- 개발자 계정 연동 프로비저닝 import

add: provisioning 등록

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum/Network/DTO/Model/Promises/AddPromiseRequestModel.swift
KkuMulKum/Network/DTO/Model/Promises/ArrivalCompletionResponseModel.swift
KkuMulKum/Network/DTO/Model/Promises/MyPromiseReadyInfoRequestModel.swift
KkuMulKum/Network/DTO/Model/Promises/MyReadyStatusResponseModel.swift
KkuMulKum/Network/DTO/Model/Promises/NearestPromiseResponseModel.swift
KkuMulKum/Network/DTO/Model/Promises/PromiseInfoResponseModel.swift
KkuMulKum/Network/DTO/Model/Promises/PromiseLateInfoResponseModel.swift
KkuMulKum/Network/DTO/Model/Promises/PromiseParticipantListResponseModel.swift
KkuMulKum/Network/DTO/Model/Promises/PromisesTemp.swift
KkuMulKum/Network/DTO/Model/Promises/UpcomingPromiseListResponseModel.swift

- Connected: #133 
- Promise 네트워크의 Request와 Response 모델을 구현했습니다.
- CodingKey와 관련된 코드 설명은 노션 링크로 빼두겠습니다!
https://arrow-frog-4b9.notion.site/2ec4942ae7bd4adb9b6075b55888b59d?pvs=4

[feat] Promise 네트워크 Request, Response Model 구현

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
KkuMulKum/Resource/Protocol/ViewModelType.swift
KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift

- Connected: #150 
- `KingFisher`와 `RxSwift` 라이브러리 추가했습니다.
- 최소 버전을 15.0으로 설정하면 일어나는 window 경고를 수정했습니다.
- `RxSwift` 라이브러리 구현을 위해 ViewModelType 프로토콜을 추가했습니다.

[hotfix] 라이브러리 추가 설치 및 경고 해결

---

KkuMulKum/Network/DTO/Model/Utils/PlaceModel.swift
KkuMulKum/Network/Service/HomeService.swift
KkuMulKum/Network/Service/MeetingService.swift
KkuMulKum/Network/Service/PromiseService.swift
KkuMulKum/Network/Service/UtilService.swift
KkuMulKum/Network/TargetType/UtilTargetType.swift
KkuMulKum/Source/AddPromise/ServiceType/FindPlaceService.swift
KkuMulKum/Source/AddPromise/ServiceType/SelectMemeberServiceType.swift
KkuMulKum/Source/AddPromise/ServiceType/SelectPenaltyService.swift
KkuMulKum/Source/AddPromise/View/FindPlaceView.swift
KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
KkuMulKum/Source/AddPromise/ViewModel/FindPlaceViewModel.swift
KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift
KkuMulKum/Source/AddPromise/ViewModel/SelectPenaltyViewModel.swift
KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift

- Connected: #220
- 약속 추가 플로우 API 연결 (코드는 Mock으로 대체되있지만, 채원이 토큰을 통해 테스트 했습니다)
- PagePromiseController 네비게이션 바가 보이지 않는 문제 해결 (@youz2me )
- 생명주기 메서드를 이용하여 hidden값을 바꿈
- 일부 메서드 수정
|    구현 내용    |   IPhone 11 Pro Max   |
| 전체 플로우 (Mock) | <img src = "https://github.com/user-attachments/assets/8a4e7644-bc83-4bcc-90d2-5d783f0909b3" width ="250"> |
| 모임 상세 | <img src = "https://github.com/user-attachments/assets/f0127180-a6f4-4d76-924f-db9ad0b46c22" width ="250"> |
| 장소 찾기 | <img src = "https://github.com/user-attachments/assets/e6c8fb03-5804-4591-80f4-e988ad7fea6e" width ="250"> |
| 찾은 장소 바인딩 | <img src = "https://github.com/user-attachments/assets/ff01b114-bab5-4ab0-b4a2-20fa3b45d659" width ="250"> |
| 약속 참여 인원 선택 | <img src = …

[feat] 약속 추가 플로우 네트워크 연결

---

KkuMulKum/Application/AppDelegate.swift
KkuMulKum/Resource/Notification/LocalNotificationManager.swift
KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
KkuMulKum/Source/AddPromise/ViewController/SelectMemberViewController.swift
KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyInfoViewController.swift
KkuMulKum/Source/Promise/ReadyStatus/ViewModel/SetReadyInfoViewModel.swift

- Connected: #245 
- 로컬알람 구현
- 유진 뷰 스크롤뷰 오류 해결
-

[feat] Local 알람 구현 완료 + 스크롤뷰 오류 해결

---

KkuMulKum/Network/TargetType/MeetingTargetType.swift
KkuMulKum/Network/TargetType/PromiseTargetType.swift
KkuMulKum/Source/AddPromise/ServiceType/SelectMemeberServiceType.swift
KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift

- Connected: #252
- 수정된 API 명세 반영
- PromiseTargetType에 fetchMeetingMemberExcludeMe 추가

[fix] 약속 추가 플로우 중 멤버 초대 화면, 나를 제외한 멤버 목록 API 반영

---

KkuMulKum/Application/SceneDelegate.swift
KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift

- Connected: #254 
- 레이아웃 오류 수정
|    구현 내용    |   IPhone 15 pro   |
| GIF | <img src = "https://github.com/user-attachments/assets/7cab9c99-c7e1-47a7-bcdf-56f727e1fe46" width ="250"> |
오류수정 성공

fix/#254 준비현황 레이아웃 수정

---

KkuMulKum/Source/Home/ViewController/HomeViewController.swift

- 오늘의 약속 없을 때 버튼 없어지게 분기처리 (현재는 서버통신 없는 약속 상세 화면으로 연결되어 데이터가 ? 처리돼서 뜸)

[hotfix/suyeon] QA 이슈 반영

---

KkuMulKum/Application/SceneDelegate.swift
KkuMulKum/Network/DTO/Model/Auth/SocialLoginResponseModel.swift
KkuMulKum/Network/Service/AuthService.swift
KkuMulKum/Network/TargetType/Auth/AuthTargetType.swift
KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift

fix/자동로그인 오류 수정

---

KkuMulKum/Source/AddPromise/ViewModel/AddPromiseViewModel.swift
KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewController/CreateMeetingViewController.swift
KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift

- Connected: #264 
- QA 반영했습니다.
- 고생하셨습니다 화이팅 ~~!

[fix] QA 반영

---

KkuMulKum/Application/SceneDelegate.swift
KkuMulKum/Network/Service/AuthService.swift
KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift

- Connected: #271 
- 멀티파트 이슈로 인해 올라가지 않던 프로필 이슈를 킹피셔를 통해 수정했습니다.

[fix] 프로필 등록하기 오류 해결

---

KkuMulKum/Network/Service/AuthService.swift

- Connected: #282 
- 머지하다가 코드 2개버전이 합쳐져서 이전버전을 지웟습니다.

[hotfix] AUthInter 오류수정

---

KkuMulKum/Application/AppDelegate.swift
KkuMulKum/Application/SceneDelegate.swift
KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
KkuMulKum/Source/Onboarding/Login/View/LoginView.swift
KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift

- Connected: #284 
- Privacy 변경
- 테스트 엑세스토큰 (자동로그인)
- 엑세스 권한 탈취이슈가 있을수도 있기에 슬랙으로 설명 갈음

[feat] 마스터 엑세스토큰 주입

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum/Network/Service/AuthService.swift
KkuMulKum/Source/Onboarding/ServiceProtocol/AuthServiceProtocol.swift

- Connected: #293 
- 이전 회의를 바탕으로 코드를 수정했습니다.

[refactor] 프로토콜 및 서비스타입 리팩

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- Connected: #292
- RxMoya (Moya 라이브러리 재설치)
- RxDataSources
- ReactorKit
- 더 필요한 내용이 있으면, 말씀해 주세요. 현재 브랜치에서 더 추가하겠습니다.

[add] 라이브러리 추가

---

KkuMulKum/Resource/ObservablePattern/ObservablePattern.swift

- Connected: #308 
- ObservablePattern에 대한 코드를 개선하였습니다.
- 이제 UI 업데이트를 위해 `DispatchQueue.main.async` 구문을 적을 필요 없습니다.
- ObservablePattern 메서드를 구현하여 메인 스레드에서 클로저(`listener`)를 동작시키도록 하였습니다.
<details>
<summary>ObservablePattern.swift</summary>
```swift
func bindOnMain(_ listener: @escaping (T) -> Void) {
self.listener = { value in
DispatchQueue.main.async {
listener(value)
}
}
}
func bindOnMain<Object: AnyObject>(with object: Object, _ listener: @escaping (Object, T) -> Void) {
self.listener = { [weak object] value in
guard let object else { return }
DispatchQueue.main.async {
listener(object, value)
}
}
}
```
</details>
- ObservablePattern이라는 네이밍이 다소 길게 느껴졌습니다.
- 또한, `bind` 메서드를 통해 변경될 값과 이후의 작업(클로저)를 바인딩하고 있기 때문에
- 네이밍을 Bindable로 변경하는 것은 어떨까 싶은데, 이와 관련해서도 의견 남겨주시면 감사하겠습니다.

[refactor] ObservablePattern 코드 개선

---

KkuMulKum/Application/SceneDelegate.swift
KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift

- Connected: #297 
- 애플로그인 관련 auth_code를 발급받았습니다.
원래 로그아웃 코드까지 같이 발급받으려 햇으나 뷰 구현이후 기능구현예정이라 이슈 삭제용으로 올립니다

[hotfix] auth_code 발금

---

KkuMulKum.xcodeproj/project.pbxproj
KkuMulKum/Source/MyPage/View/MyPageEditView.swift
KkuMulKum/Source/MyPage/ViewController/MyPageAskViewController.swift
KkuMulKum/Source/MyPage/ViewController/MyPageEditViewController.swift
KkuMulKum/Source/MyPage/ViewController/MyPageTermsViewController.swift
KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
KkuMulKum/Source/MyPage/ViewModel/MyPageEditViewModel.swift

- Connected: #321 
- 프로필 이미지 수정 뷰 구현
- 프로필 이미지 rx바인딩
- 프로필 이용약관 로딩
- 프로필 문의하기 로딩
|    구현 내용    |   IPhone 15 pro   |
| GIF | <img src = "https://github.com/user-attachments/assets/7296ff6b-bc53-4da8-8234-c7a8b560a403" width ="250"> |

[feat] 웹뷰 로딩하기

---

KkuMulKum/Source/AddMeeting/CheckInviteCode/View/CheckInviteCodeView.swift
KkuMulKum/Source/AddMeeting/CheckInviteCode/View/JoinButtonView.swift

- Connected: #327 
- 디자인 명세에 따라 안내 텍스트, 모서리 값, 오토 레이아웃을 수정했습니다.
|    구현 내용    |   IPhone 15 pro   |
| PNG | <img src = "https://github.com/user-attachments/assets/44b79c32-a865-4ff1-b223-ae8324b5dd9b" width ="250"> |
JoinButtonView 컴포넌트와 해당 컴포넌트를 상속한 뷰를 제외하고는 수정하지 않았습니다. 해당 뷰를 포함하여 전체적인 모임 추가 플로우에 수정된 행간 익스텐션에 따라 디자인 명세에 맞게 오토레이아웃을 수정하는 작업이 필요해보입니다! (@youz2me)

[fix] 모임 추가 플로우 QA 반영

---

KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseContentViewController.swift
KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseMemberViewController.swift
KkuMulKum/Source/Promise/EditPromise/ViewModel/EditPromiseViewModel.swift
KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift

- Connected: #345
- 내가 속한 약속 여부에 따라 편집 버튼 분기 처리했습니다.
- 약속 정보 뷰에서 D-Day 시간 계산 로직 수정 및 남은 날임 음수로 띄워지는 문제 해결했습니다.
- 지각 마치기 세부 분기 처리 진행했습니다.
- 약속 수정 뷰 셀 선택 안되는 문제 해결했습니다. (@JinUng41 감사합니다 🙇‍♀️)
- 약속 수정 API 분기 처리 및 observable pattern에 맞게 리팩토링 진행했습니다. (@JinUng41 감사합니다 🙇‍♀️)
- 이제 진짜 QA 할 수 있겠네요 🫠 작업이 늦어져서 죄송합니다 🥹

[refactor] 내가 속한 약속 분기 처리 및 자잘한 오류 수정
